name: Feature Request
description: Suggest a new feature for TMDbAPIs.
title: '[Feature]: '
labels: ['status:not-yet-viewed', 'enhancement']
assignees: 'meisnate12'

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: textarea
    id: problem-relation
    attributes:
      label: Is your feature request related to a problem? Please elaborate.
      description: A clear and concise description of what the problem is.
      placeholder: eg. I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "[optional] You may provide additional context or screenshots for us to better understand the need of the feature."
