name: Documentation Request
description: A request to update or improve TMDbAPIs' documentation
title: '[Docs]: '
labels: ['status:not-yet-viewed', 'documentation']
assignees: 'meisnate12'

body:
  - type: textarea
    attributes:
      label: What is the improvement or update to the Documentation you wish to see?
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://tmdbapis.kometa.wiki/en/latest/objapi.html'
    validations:
      required: false