name: PyPI Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Create Release for new Tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ secrets.REPO_NAME }} ${{ github.event.ref }}
          repo_token: ${{ secrets.PAT }}
          prerelease: false

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          pip install --no-cache-dir --upgrade --requirement requirements.txt

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

      - name: Discord Success Notification
        uses: Kometa-Team/discord-notifications@master
        if: success()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          title: "${{ secrets.REPO_NAME }} ${{ github.event.ref }}: **Build Successful**"
          url: https://github.com/Kometa-Team/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: 844716
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/develop/.github/logo.png
          author: PyPI
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/develop/.github/pypi.svg

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        if: failure()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          message: <@&1079153184007790652>
          title: "${{ secrets.REPO_NAME }} ${{ github.event.ref }}: **Build Failed**"
          color: 14879811
          url: https://github.com/Kometa-Team/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/logo.png
          author: PyPI
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/develop/.github/pypi.svg