name: Release

on:
  create:
    tags:
      - v*

jobs:
  tagged-release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Create Release for new Tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: TMDbAPIs ${{ github.event.ref }}
          repo_token: ${{ secrets.PAT }}
          prerelease: false

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          pip install --no-cache-dir --upgrade --requirement requirements.txt

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
