name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  run:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .

      - name: Run Tests
        env:
          TMDB_APIKEY: ${{ secrets.TMDB_APIKEY }}
          TMDB_SESSION: ${{ secrets.TMDB_SESSION }}
          TMDB_V4_ACCESS: ${{ secrets.TMDB_V4_ACCESS }}
          TMDB_V4_TOKEN: ${{ secrets.TMDB_V4_TOKEN }}
          TMDB_USERNAME: ${{ secrets.TMDB_USERNAME }}
          TMDB_PASSWORD: ${{ secrets.TMDB_PASSWORD }}
          PAT: ${{ secrets.PAT }}
          LOCAL: False
        run: pytest -s --cov=tmdbapis --cov-report=xml tests/test*

      - name: Codecov coverage reports
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  failure-notification:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [run]
    steps:

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: ${{ vars.BUILD_FAILURE_ROLE }}
          title: "${{ vars.NAME }}: ${{ vars.TEXT_COPYRIGHT }}"
          url: https://github.com/Kometa-Team/${{ vars.NAME }}/actions/runs/${{ github.run_id }}
          color: ${{ vars.COLOR_FAILURE }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.GIT_NAME }}
          author_icon_url: ${{ vars.GIT_IMAGE }}
